name: loanlink
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.2
  country_picker: ^2.0.20
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+4
  pinput: ^2.2.31
  provider: ^6.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lottie: ^2.3.2
flutter:
  uses-material-design: true
  assets:
    - assets/
